Layout/Tab:
  Enabled: false
IndentationWidth:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false